disabledplugins:
  - AssassinHut
  - AxolotlOP
  - BlockShuffle
  - blockwalk
  - chunkminer
  - CrouchExplode
  - CustomCommandBlocks
  - CustomEnchants
  - CustomHoes
  - CustomPots
  - CustomTNT
  - DeathSwap
  - Dreamcompass
  - eggsop
  - EnchantmentWalk
  - EnchantsIncreased
  - FallingBlocks
  - farmingop
  - FishingOP
  - FishingStructures
  - GravityBlocks
  - GrowBiomes
  - HealthStack
  - InventoryShrink
  - Itemmultiply
  - LavaRain
  - ManHunt
  - MCParrot
  - MinecraftDog
  - MinecraftForcefield
  - MobLookMultiply
  - multipliedcrafting
  - MultiplyingBlocks
  - NetherOnlyManhunt
  - OPAnvil
  - OPShearing
  - PiglinTradeStructures
  - RandomBlockLook
  - SiameseTrios
  - SiameseTwins
  - SleepingOP
  - TapLStructuresEachMinute
  - TNTMultiplier
  - TradeMultiply
  - WorldController
  - worldedit
  
reload_message: "Reloaded the config!"
